const students = [
	{ id: 2, name: "Aidin", image: "images/students/aidin_radjavi.jpg" },
	{ id: 3, name: "Alexander", image: "images/students/alexander_hamming.jpg" },
	{ id: 4, name: "Ali", image: "images/students/ali_rezai.jpg" },
	{ id: 6, name: "Andreas", image: "images/students/andreas_thorner.jpg" },
	{ id: 7, name: "Angelica", image: "images/students/angelica_dahlberg.jpg" },
	{ id: 8, name: "Ann", image: "images/students/ann_bacharach.jpg" },
	{ id: 9, name: "Anna", image: "images/students/anna_brynhagen.jpg" },
	{ id: 10, name: "Camilla", image: "images/students/camilla_landin.jpg" },
	{ id: 11, name: "Carolin H.", image: "images/students/carolin_hansson.jpg" },
	{ id: 12, name: "Caroline R.", image: "images/students/caroline_roos_bergman.jpg" },
	{ id: 13, name: "Denis", image: "images/students/denis_imamovic.jpg" },
	{ id: 14, name: "Elin", image: "images/students/elin_ny.jpg" },
	{ id: 15, name: "Ellinor", image: "images/students/ellinor_lindstrom.jpg" },
	{ id: 16, name: "Emma Q.", image: "images/students/emma_quinn.jpg" },
	{ id: 17, name: "Emma Å.", image: "images/students/emma_ahlander_klinteberg.jpg" },
	{ id: 18, name: "Erik L.", image: "images/students/erik_lindestad.jpg" },
	{ id: 20, name: "Fanny", image: "images/students/fanny_hoberg.jpg" },
	{ id: 21, name: "Hanna", image: "images/students/hanna_soderholm.jpg" },
	{ id: 22, name: "Johan", image: "images/students/johan_kremer.jpg" },
	{ id: 25, name: "Josefin A.", image: "images/students/josefin_ahlenius.jpg" },
	{ id: 26, name: "Josefine P.", image: "images/students/josefine_pettersson.jpg" },
	{ id: 27, name: "Karin", image: "images/students/karin_rasmusson.jpg" },
	{ id: 28, name: "Khaled", image: "images/students/khaled_hassan.jpg" },
	{ id: 29, name: "Leonid", image: "images/students/leonid_markovski.jpg" },
	{ id: 30, name: "Linnea M.", image: "images/students/linnea_magnusson.jpg" },
	{ id: 31, name: "Linnea S.", image: "images/students/linnea_sandberg.jpg" },
	{ id: 32, name: "Madeleine", image: "images/students/madeleine_matis.jpg" },
	{ id: 33, name: "Mattea", image: "images/students/mattea_saxell.jpg" },
	{ id: 34, name: "Max", image: "images/students/max_reichenauer.jpg" },
	{ id: 35, name: "Mohsen", image: "images/students/mohsen_heidari.jpg" },
	{ id: 37, name: "Oscar", image: "images/students/oscar_throedsson.jpg" },
	{ id: 38, name: "Petar", image: "images/students/petar_gorgievski.jpg" },
	{ id: 39, name: "Peter", image: "images/students/peter_hyllengren.jpg" },
	{ id: 40, name: "Pontus", image: "images/students/pontus_ekberg.jpg" },
	{ id: 41, name: "Pucha", image: "images/students/pucha_sayerz_olsen.jpg" },
	{ id: 42, name: "Ramil", image: "images/students/rameel_siddiqui.jpg" },
	{ id: 45, name: "Tomasz", image: "images/students/tomasz_polrolniczak.jpg" },
	{ id: 43, name: "Robin", image: "images/students/robin_persson.jpg" },
	{ id: 44, name: "Sofia", image: "images/students/sofia_pasco.jpg" },
	{ id: 47, name: "Victor", image: "images/students/victor_svensson.jpg" },
	{ id: 48, name: "William", image: "images/students/william_lam.jpg" },
];

const missing_students = [
	{ id: 1, name: "Adam", image: "assets/images/students/adam_aspdahl_mourad.jpg" },
	{ id: 5, name: "Amin", image: "assets/images/students/amin_hassani.jpg" },
	{ id: 19, name: "Erik T.", image: "assets/images/students/erik_toft.jpg" },
	{ id: 22, name: "Jacob", image: "assets/images/students/jacob_lloyd.jpg" },
	{ id: 23, name: "Joakim", image: "assets/images/students/joakim_astrom.jpg" },
	{ id: 36, name: "Nichlas", image: "assets/images/students/nichlas_wijk.jpg" },
	{ id: 46, name: "Torbjörn", image: "assets/images/students/torbjorn_grahn.jpg" },
];
